# ___

# DataFrames

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

## About this notebook

A **DataFrame** is a table: rows have labels (the *index*) and columns have names. It is the object you will use most in data science. Here you will learn how to select columns and rows, add and remove columns, filter rows with conditions, change the index, and work with a two-level (*multi*) index.

**How to use it:** click a code cell and press **Shift + Enter** to run it. Run the cells from top to bottom, because later cells use things created in earlier ones. The short note above each code cell tells you what it does.

Import pandas and NumPy, as in every pandas notebook.

In [1]:
import pandas as pd
import numpy as np

`randn` creates random numbers. Setting the **seed** to 101 makes the "random" numbers the same every time you run the notebook, so your results match everyone else's.

In [2]:
from numpy.random import randn
np.random.seed(101)

Create a DataFrame of 5 rows by 4 columns filled with random numbers. The rows are labelled **A to E** and the columns **W, X, Y, Z**. (`'A B C D E'.split()` is a quick way to write the list `['A','B','C','D','E']`.)

In [3]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

Display the table.

In [4]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

Select one column by putting its name in square brackets. A single column comes back as a **Series**.

In [5]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

To select several columns, pass a **list** of names. Note the double brackets: the outer ones select, the inner ones make the list. The result is a smaller DataFrame.

In [6]:
# Pass a list of column names
df[['W','Z']]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

You can also select a column with a dot, like `df.W`. It works, but it is not recommended: it fails if the column name contains a space or has the same name as a pandas method. Prefer `df['W']`.

In [7]:
# SQL Syntax (NOT RECOMMENDED!)
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

DataFrame Columns are just Series

Check the type of a single column: it is a pandas **Series**. A DataFrame is really a set of Series that share the same row labels.

In [8]:
type(df['W'])

pandas.Series

**Creating a new column:**

Create a **new column** called `new` by adding columns W and Y, row by row.

In [9]:
df['new'] = df['W'] + df['Y']

The table now has a fifth column, `new`.

In [10]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

** Removing Columns**

Remove the column `new`. `axis=1` means "look for a **column** with this name" (`axis=0` would mean a row). The result is shown without `new`...

In [11]:
df.drop('new',axis=1)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

...but the original table has **not** changed: `new` is still there. Most pandas methods return a new copy and leave the original untouched.

In [12]:
# Not inplace unless specified!
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

To change the original table itself, add `inplace=True`. This cell shows nothing because it modifies `df` directly.

In [13]:
df.drop('new',axis=1,inplace=True)

Now the column `new` is really gone.

In [14]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

Can also drop rows this way:

Drop a **row** instead, by using its label and `axis=0`. (Again this is not in place, so `df` still has row E.)

In [15]:
df.drop('E',axis=0)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

** Selecting Rows**

`.loc[...]` selects rows **by label**. Here we get row A, returned as a Series.

In [16]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

Or select based off of position instead of label

`.iloc[...]` selects rows **by position**, counting from 0. Position 2 is the third row, which is row C.

In [17]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

** Selecting subset of rows and columns **

With `.loc[row, column]` you can pick a single value: the one in row B, column Y.

In [18]:
df.loc['B','Y']

np.float64(-0.8480769834036315)

Pass lists to get a smaller block of the table: rows A and B, columns W and Y.

In [19]:
df.loc[['A','B'],['W','Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

Display the table again, as a reminder before we start filtering.

In [20]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

Comparing the whole table with a number gives a table of **True/False** values: True wherever the value is greater than 0.

In [21]:
df>0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

Using that True/False table inside the brackets keeps the values where it is True and replaces the rest with **NaN**.

In [22]:
df[df>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

More useful in practice: keep only the **rows** where column W is greater than 0. Rows with a negative W disappear.

In [23]:
df[df['W']>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

You can chain selections: first filter the rows where W > 0, then take column Y from the result.

In [24]:
df[df['W']>0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

Same idea, but take two columns, Y and X, from the filtered rows.

In [25]:
df[df['W']>0][['Y','X']]

          Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

For two conditions you can use | and & with parenthesis:

Combine two conditions with **`&`** (and) or **`|`** (or). Each condition must be inside its own parentheses. Here we keep rows where W > 0 **and** Y > 1. (Python's words `and`/`or` do not work here.)

In [26]:
df[(df['W']>0) & (df['Y'] > 1)]

          W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

Display the table again before changing its index.

In [27]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

`reset_index()` turns the row labels (A to E) into an ordinary column called `index`, and numbers the rows 0, 1, 2... instead. Not in place, so `df` itself is unchanged.

In [28]:
# Reset to default 0,1...n index
df.reset_index()

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

A quick way to make the list `['CA', 'NY', 'WY', 'OR', 'CO']` of US state codes.

In [29]:
newind = 'CA NY WY OR CO'.split()

Add that list to the table as a new column called `States` (one value per row).

In [30]:
df['States'] = newind

The table now has a `States` column.

In [31]:
df

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

`set_index('States')` uses the `States` column as the row labels instead of A to E. Again, this only shows the result...

In [32]:
df.set_index('States')

               W         X         Y         Z
States
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

...and `df` is unchanged.

In [33]:
df

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

With `inplace=True` the change is made to `df` itself.

In [34]:
df.set_index('States',inplace=True)

Now the rows are labelled by state.

In [35]:
df

               W         X         Y         Z
States
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

Now we build a **multi-index**: row labels with two levels, like chapters and sections. The outer level is the group (G1, G2) and the inner level is a number (1, 2, 3). `zip` pairs them up as (G1, 1), (G1, 2) and so on, and `MultiIndex.from_tuples` turns those pairs into an index.

In [36]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

Display the multi-index we just built: six pairs of labels.

In [37]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

Create a DataFrame of random numbers with two columns (A and B) that uses the two-level index for its rows.

In [38]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

             A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

Now let's show how to index this! For index hierarchy we use df.loc[], if this was on the columns axis, you would just use normal bracket notation df[]. Calling one level of the index returns the sub-dataframe:

`.loc['G1']` selects the **outer** level: all rows that belong to group G1.

In [39]:
df.loc['G1']

          A         B
1  0.302665  1.693723
2 -1.706086 -1.159119
3 -0.134841  0.390528

Go one level deeper: from group G1, take the row with inner label 1. The result is a single row (a Series).

In [40]:
df.loc['G1'].loc[1]

A    0.302665
B    1.693723
Name: 1, dtype: float64

`index.names` shows the names of the two index levels. They are `None` because we have not named them yet.

In [41]:
df.index.names

FrozenList([None, None])

Give the two levels names: **Group** for the outer level and **Num** for the inner one.

In [42]:
df.index.names = ['Group','Num']

The level names now appear above the row labels.

In [43]:
df

                  A         B
Group Num
G1    1    0.302665  1.693723
      2   -1.706086 -1.159119
      3   -0.134841  0.390528
G2    1    0.166905  0.184502
      2    0.807706  0.072960
      3    0.638787  0.329646

`.xs()` (short for *cross-section*) is another way to select from a multi-index. `xs('G1')` gives all rows of group G1, the same as `.loc['G1']`.

In [44]:
df.xs('G1')

            A         B
Num
1    0.302665  1.693723
2   -1.706086 -1.159119
3   -0.134841  0.390528

Select one exact row by giving both labels as a pair (a **tuple**): group G1, number 1.

In [45]:
df.xs(('G1',1))

A    0.302665
B    1.693723
Name: (G1, 1), dtype: float64

This is where `xs` is really handy: it can select from the **inner** level. Here we take the row with Num = 1 from **every** group, which is hard to do with `.loc`.

In [46]:
df.xs(1,level='Num')

              A         B
Group
G1     0.302665  1.693723
G2     0.166905  0.184502

# Great Job!