# ___

# Missing Data

Let's show a few convenient methods to deal with Missing Data in pandas:

## About this notebook

Real data often has gaps. In pandas a missing value is shown as **NaN** ("Not a Number"). This notebook shows the two basic ways to deal with it: **drop** the rows or columns that contain gaps (`dropna`), or **fill** the gaps with a value of your choice (`fillna`).

**How to use it:** click a code cell and press **Shift + Enter** to run it. Run the cells from top to bottom, because later cells use things created in earlier ones. The short note above each code cell tells you what it does.

Import NumPy and pandas. We need NumPy for `np.nan`, which is how we write a missing value.

In [1]:
import numpy as np
import pandas as pd

Build a small table with some gaps: column A has one missing value, column B has two, and column C is complete.

In [2]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

Display the table. The missing values are shown as **NaN**.

In [3]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

`dropna()` removes every **row** that has at least one missing value. Only row 0 is complete, so only row 0 is left.

In [4]:
df.dropna()

     A    B  C
0  1.0  5.0  1

With `axis=1`, `dropna` removes every **column** that has a missing value instead. Only column C is complete.

In [5]:
df.dropna(axis=1)

   C
0  1
1  2
2  3

`thresh=2` means "keep a row only if it has **at least 2 real (non-missing) values**". Row 0 has 3 and row 1 has 2, so they stay. Row 2 has only 1, so it is dropped.

In [6]:
df.dropna(thresh=2)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

`fillna()` replaces every missing value with the value you give, here the text `'FILL VALUE'`. In real work you would usually fill with a number instead.

In [7]:
df.fillna(value='FILL VALUE')

            A           B  C
0         1.0         5.0  1
1         2.0  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

A common, more sensible approach: fill the gaps in column A with the **average (mean)** of that column. The mean of 1 and 2 is 1.5, so the missing value becomes 1.5. (This shows the result; it does not change `df`.)

In [8]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

# Great Job!