# ___

# Operations

There are lots of operations with pandas that will be really useful to you, but don't fall into any distinct category. Let's show them here in this lecture:

## About this notebook

A collection of everyday pandas tools that you will use again and again: finding unique values, counting how often each value appears, filtering rows, applying your own function to a column, deleting columns, sorting, finding missing values, and building a pivot table.

**How to use it:** click a code cell and press **Shift + Enter** to run it. Run the cells from top to bottom, because later cells use things created in earlier ones. The short note above each code cell tells you what it does.

Import pandas, create a small example table and show it. `head()` displays the first five rows, which is the usual way to take a quick look at a table.

In [1]:
import pandas as pd
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

### Info on Unique Values

`unique()` lists the **different** values in column `col2`, each one only once.

In [2]:
df['col2'].unique()

array([444, 555, 666])

`nunique()` counts **how many** different values there are.

In [3]:
df['col2'].nunique()

3

`value_counts()` shows how many times each value appears. Here 444 appears twice.

In [4]:
df['col2'].value_counts()

col2
444    2
555    1
666    1
Name: count, dtype: int64

### Selecting Data

Filter rows using two columns at once: keep rows where `col1` is greater than 2 **and** `col2` equals 444. The result is stored in `newdf`.

In [5]:
#Select from DataFrame using criteria from multiple columns
newdf = df[(df['col1']>2) & (df['col2']==444)]

Display the filtered rows.

In [6]:
newdf

   col1  col2 col3
3     4   444  xyz

### Applying Functions

Define our own small function that doubles a number.

In [7]:
def times2(x):
    return x*2

`apply()` runs a function on **every value** of a column. Here each value of `col1` is doubled.

In [8]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

`apply()` works with built-in functions too: `len` gives the length of each piece of text in `col3`.

In [9]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

Add up all the values in `col1`.

In [10]:
df['col1'].sum()

np.int64(10)

** Permanently Removing a Column**

`del` deletes the column `col1` **permanently** (in place, no copy is made).

In [11]:
del df['col1']

The table now has only `col2` and `col3`.

In [12]:
df

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

** Get column and index names: **

`df.columns` lists the column names.

In [13]:
df.columns

Index(['col2', 'col3'], dtype='str')

`df.index` describes the row labels. `RangeIndex(start=0, stop=4, step=1)` simply means the rows are numbered 0, 1, 2, 3.

In [14]:
df.index

RangeIndex(start=0, stop=4, step=1)

** Sorting and Ordering a DataFrame:**

Display the table again before sorting.

In [15]:
df

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

`sort_values(by='col2')` sorts the rows from the smallest to the largest value of `col2`. Notice that the row labels move along with their rows. (`df` itself is not changed.)

In [16]:
df.sort_values(by='col2') #inplace=False by default

   col2 col3
0   444  abc
3   444  xyz
1   555  def
2   666  ghi

** Find Null Values or Check for Null Values**

`isnull()` checks every cell and shows **True** where a value is missing. This table has no gaps, so everything is False.

In [17]:
df.isnull()

    col2   col3
0  False  False
1  False  False
2  False  False
3  False  False

`dropna()` removes rows with missing values. There are none here, so the table comes back unchanged.

In [18]:
# Drop rows with NaN Values
df.dropna()

   col2 col3
0   444  abc
1   555  def
2   666  ghi
3   444  xyz

** Filling in NaN values with something else: **

Import NumPy, which we need for `np.nan` (a missing value).

In [19]:
import numpy as np

Create a new table that **does** contain missing values (NaN) and display it.

In [20]:
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

   col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

`fillna('FILL')` replaces every missing value with the text `'FILL'`.

In [21]:
df.fillna('FILL')

   col1   col2 col3
0   1.0   FILL  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3  FILL  444.0  xyz

Create a new table for the pivot table example: columns A, B and C hold categories, and column D holds numbers.

In [22]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

Display the table.

In [23]:
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

A **pivot table** reorganises the data into a summary grid, as in Excel. Here the rows are the combinations of A and B, the columns are the values of C (x and y), and each cell shows the value of D (the average, if there were several). Combinations that do not exist in the data show **NaN**.

In [24]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C          x    y
A   B
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

# Great Job!