# ___

# Data Input and Output

This notebook is the reference code for getting input and output, pandas can read a variety of file types using its pd.read_ methods. Let's take a look at the most common data types:

## About this notebook

Before you can analyse data you have to load it, and afterwards you often want to save it. This notebook shows how pandas **reads** and **writes** the most common formats: CSV files, Excel files, HTML tables and SQL databases. Every `pd.read_...` function gives you a DataFrame, and every `df.to_...` method saves one.

**Heads-up:** a few cells *save* files (`to_csv`, `to_excel`, `to_html`) into the same folder as this notebook, so `example.csv` and `excel_sample.xlsx` are overwritten when you run it.

**How to use it:** click a code cell and press **Shift + Enter** to run it. Run the cells from top to bottom, because later cells use things created in earlier ones. The short note above each code cell tells you what it does.

Import NumPy and pandas.

In [1]:
import numpy as np
import pandas as pd

## CSV

### CSV Input

`pd.read_csv` reads a CSV file (a plain-text file with values separated by commas) into a DataFrame. `example.csv` sits in the same folder as this notebook.

In [2]:
df = pd.read_csv('example.csv')
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

### CSV Output

`to_csv` saves the DataFrame as a CSV file. `index=False` means the row numbers are not written as an extra column. Note that this **overwrites** `example.csv`.

In [3]:
df.to_csv('example.csv',index=False)

## Excel
Pandas can read and write excel files, keep in mind, this only imports data. Not formulas or images, having images or macros may cause this read_excel method to crash.

### Excel Input

`pd.read_excel` reads one sheet of an Excel file into a DataFrame. `sheet_name` chooses which sheet to read.

In [4]:
pd.read_excel('excel_sample.xlsx',sheet_name='Sheet1')

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

### Excel Output

`to_excel` saves the DataFrame as an Excel file, here into a sheet called Sheet1. This overwrites `excel_sample.xlsx`.

In [5]:
df.to_excel('excel_sample.xlsx',sheet_name='Sheet1')

## HTML

Pandas can read tables from HTML pages. It needs the `beautifulsoup4` and `html5lib` (or `lxml`) packages, which are already installed in this course environment.

> **Note:** this notebook runs inside your web browser, which cannot download pages from other websites. So instead of reading a live web page, we first save a table as an HTML file and then read it back, exactly as `read_html` would read a page you saved from the web.

### HTML Input

Pandas read_html function will read tables off of a webpage and return a list of DataFrame objects:

`read_html` looks for **tables** on a web page and returns a **list** of DataFrames, one per table it finds. Here we first save our own DataFrame as an HTML file (`to_html`) and then read it back. `len(tables)` shows how many tables were found: just 1.

In [6]:
# Save our DataFrame as an HTML table, then read it back.
# (On your own computer you could pass a web address or a saved .html page instead.)
df.to_html('example_table.html', index=False)
tables = pd.read_html('example_table.html', flavor='bs4')
len(tables)  # read_html returns a LIST of tables

1

Take the first (and only) table from the list. Python counts from 0, so the first item is `tables[0]`.

In [7]:
tables[0]

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

____

_____
_____
# SQL (Optional)

* Note: If you are completely unfamiliar with SQL you can check out my other course: "Complete SQL Bootcamp" to learn SQL.

The pandas.io.sql module provides a collection of query wrappers to both facilitate data retrieval and to reduce dependency on DB-specific API. Database abstraction is provided by SQLAlchemy if installed. In addition you will need a driver library for your database. Examples of such drivers are psycopg2 for PostgreSQL or pymysql for MySQL. For SQLite this is included in Python’s standard library by default. You can find an overview of supported drivers for each SQL dialect in the SQLAlchemy docs.


If SQLAlchemy is not installed, a fallback is only provided for sqlite (and for mysql for backwards compatibility, but this is deprecated and will be removed in a future version). This mode requires a Python database adapter which respect the Python DB-API.

See also some cookbook examples for some advanced strategies.

The key functions are:

* read_sql_table(table_name, con[, schema, ...])	
    * Read SQL database table into a DataFrame.
* read_sql_query(sql, con[, index_col, ...])	
    * Read SQL query into a DataFrame.
* read_sql(sql, con[, index_col, ...])	
    * Read SQL query or database table into a DataFrame.
* DataFrame.to_sql(name, con[, flavor, ...])	
    * Write records stored in a DataFrame to a SQL database.

> **In this course** we connect with Python's built-in `sqlite3` module, so no extra database package is needed. On your own computer you can also use SQLAlchemy: `from sqlalchemy import create_engine` and `engine = create_engine('sqlite:///:memory:')`.

Import `sqlite3`, the small database engine that comes built into Python.

In [8]:
import sqlite3  # SQLite comes built into Python

Open a connection to a temporary database. `':memory:'` means it lives only in the computer's memory and disappears when the notebook is closed.

In [9]:
engine = sqlite3.connect(':memory:')  # a temporary database that lives in memory

`to_sql` saves the DataFrame as a table called `data` inside the database. The number it prints is how many rows were written.

In [10]:
df.to_sql('data', engine)

4

`pd.read_sql` runs an SQL query and returns the answer as a DataFrame. `SELECT * FROM data` means "give me every column of every row from the table `data`".

In [11]:
sql_df = pd.read_sql('SELECT * FROM data', con=engine)

Display the result: the same data, now read back from the database. The extra `index` column holds the row numbers, which `to_sql` saved as well (add `index=False` to `to_sql` if you do not want them).

In [12]:
sql_df

   index   a   b   c   d
0      0   0   1   2   3
1      1   4   5   6   7
2      2   8   9  10  11
3      3  12  13  14  15

# Great Job!